In [ ]:
import numpy as np 
import pandas as pd

In [ ]:
df=pd.read_csv("/content/covid.csv")

In [ ]:
df.head()

no   pc     wbc      mc   ast      bc     ldh  diagnosis
0   1  Low     Low     Low  High  Normal  Normal       True
1   2  Low     Low  Normal  High  Normal    High       True
2   3  Low    High  Normal  High  Normal  Normal      False
3   4  Low    High  Normal  High    High  Normal       True
4   5  Low  Normal    High  High  Normal  Normal      False

In [ ]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
pc_encoded=le.fit_transform(df['pc'].values)
wbc_encoded=le.fit_transform(df['wbc'].values)
mc_encoded=le.fit_transform(df['mc'].values)
ast_encoded=le.fit_transform(df['ast'].values)
bc_encoded=le.fit_transform(df['bc'].values)
ldh_encoded=le.fit_transform(df['ldh'].values)
Y=le.fit_transform(df['diagnosis'].values)

In [ ]:
X=np.array(list(zip(pc_encoded,wbc_encoded,mc_encoded,ast_encoded,bc_encoded,ldh_encoded)))
print(X)
print(Y)

[[1 1 1 0 1 1]
 [1 1 2 0 1 0]
 [1 0 2 0 1 1]
 [1 0 2 0 0 1]
 [1 2 0 0 1 1]
 [1 2 2 0 1 0]
 [2 1 1 0 1 1]
 [2 0 2 0 1 1]
 [2 0 2 0 0 0]
 [2 2 0 0 1 1]
 [2 2 0 0 1 0]
 [0 1 1 1 1 1]
 [0 2 0 1 1 1]
 [0 2 0 1 0 0]
 [0 0 2 1 1 0]
 [1 2 0 0 0 1]
 [2 2 0 0 0 1]
 [0 1 1 1 1 0]
 [2 2 2 0 1 1]
 [2 0 2 0 1 0]
 [2 1 2 0 1 0]
 [1 0 2 0 0 0]
 [1 1 1 0 0 0]
 [0 0 2 1 1 1]
 [0 2 2 1 1 1]]
[1 1 0 1 0 1 1 0 1 0 1 1 0 1 1 0 0 1 0 1 1 1 1 1 0]


In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
model = MultinomialNB()

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y)

In [ ]:
model.fit(X_train, Y_train)
y_pred = model.predict(X_test)
print("Accuracy:",accuracy_score(Y_test, y_pred))
print("\nReport")
print(classification_report(Y_test,y_pred))

Accuracy: 0.8571428571428571

Report
              precision    recall  f1-score   support

           0       0.67      1.00      0.80         2
           1       1.00      0.80      0.89         5

    accuracy                           0.86         7
   macro avg       0.83      0.90      0.84         7
weighted avg       0.90      0.86      0.86         7

