In [1]:
from sklearn.svm import SVC
from sklearn import svm
import numpy as np

X=np.array([[3,4],[1,4],[2,3],[6,-1],[7,-1],[5,-3]])
y=np.array([-1,-1,-1,1,1,1])

l=SVC(C=1e5,kernel='linear')
l.fit(X,y)

print('w= ',l.coef_)
print('b= ',l.intercept_)
print('Indices of support vectors= ',l.support_)
print('Support vectors= ',l.support_vectors_)
print('No. of support vectors fro each class= ',l.n_support_)
print('coefficient of support vectors in decision function= ',np.abs(l.dual_coef_))

w=  [[ 0.25 -0.25]]
b=  [-0.75]
Indices of support vectors=  [2 3]
Support vectors=  [[ 2.  3.]
 [ 6. -1.]]
No. of support vectors fro each class=  [1 1]
coefficient of support vectors in decision function=  [[0.0625 0.0625]]


In [2]:
import pandas as pd
data=pd.read_csv(r'/content/glass.csv')
data.head()

Id       RI     Na    Mg    Al    Si      K    Ca   Ba   Fe  Type
0   1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1   2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2   3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3   4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4   5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [3]:
x=data.drop('Type',axis=1)
y=data.Type

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [5]:
linear=svm.SVC(kernel='linear')
linear.fit(x_train,y_train)

SVC(kernel='linear')

In [6]:
print(linear.support_vectors_)

[[7.00000e+01 1.52300e+00 1.33100e+01 3.58000e+00 8.20000e-01 7.19900e+01
  1.20000e-01 1.01700e+01 0.00000e+00 3.00000e-02]
 [1.45000e+02 1.51660e+00 1.29900e+01 3.18000e+00 1.23000e+00 7.29700e+01
  5.80000e-01 8.81000e+00 0.00000e+00 2.40000e-01]
 [7.20000e+01 1.51848e+00 1.36400e+01 3.87000e+00 1.27000e+00 7.19600e+01
  5.40000e-01 8.32000e+00 0.00000e+00 3.20000e-01]
 [1.63000e+02 1.52211e+00 1.41900e+01 3.78000e+00 9.10000e-01 7.13600e+01
  2.30000e-01 9.14000e+00 0.00000e+00 3.70000e-01]
 [1.48000e+02 1.51610e+00 1.33300e+01 3.53000e+00 1.34000e+00 7.26700e+01
  5.60000e-01 8.33000e+00 0.00000e+00 0.00000e+00]
 [1.65000e+02 1.51915e+00 1.27300e+01 1.85000e+00 1.86000e+00 7.26900e+01
  6.00000e-01 1.00900e+01 0.00000e+00 0.00000e+00]
 [1.75000e+02 1.52058e+00 1.28500e+01 1.61000e+00 2.17000e+00 7.21800e+01
  7.60000e-01 9.70000e+00 2.40000e-01 5.10000e-01]
 [1.64000e+02 1.51514e+00 1.40100e+01 2.68000e+00 3.50000e+00 6.98900e+01
  1.68000e+00 5.87000e+00 2.20000e+00 0.00000e+00]


In [7]:
print(linear.n_support_)

[1 2 2 3 3 2]


In [8]:
y_pred=linear.predict(x_test)

In [9]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

1.0


In [10]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[21  0  0  0  0  0]
 [ 0 19  0  0  0  0]
 [ 0  0  5  0  0  0]
 [ 0  0  0  2  0  0]
 [ 0  0  0  0  3  0]
 [ 0  0  0  0  0 15]]


In [11]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        21
           2       1.00      1.00      1.00        19
           3       1.00      1.00      1.00         5
           5       1.00      1.00      1.00         2
           6       1.00      1.00      1.00         3
           7       1.00      1.00      1.00        15

    accuracy                           1.00        65
   macro avg       1.00      1.00      1.00        65
weighted avg       1.00      1.00      1.00        65



In [12]:
#with different kernels
model1=SVC(kernel='sigmoid')
model2=SVC(kernel='poly')
model3=SVC(kernel='rbf')

In [13]:
model1.fit(x_train,y_train)
model2.fit(x_train,y_train)
model3.fit(x_train,y_train)

SVC()

In [14]:
y_pred1=model1.predict(x_test)

In [15]:
y_pred2=model2.predict(x_test)

In [16]:
y_pred3=model3.predict(x_test)

In [17]:
print(accuracy_score(y_test,y_pred1))

0.5846153846153846


In [18]:
print(accuracy_score(y_test,y_pred2))

0.9692307692307692


In [19]:
print(accuracy_score(y_test,y_pred3))

0.8461538461538461
